import badkeys

from api import rsa_w
from tests.core import util

_DEBIAN_SSL = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAwJZTDExKND/DiP+LbhTIi2F0hZZt0PdX897LLwPf3+b1GOCUj1OH
BZvVqhJPJtOPE53W68I0NgVhaJdY6bFOA/cUUIFnN0y/ZOJOJsPNle1aXQTjxAS+
FXu4CQ6a2pzcU+9+gGwed7XxAkIVCiTprfmRCI2vIKdb61S8kf5D3YdVRH/Tq977
nxyYeosEGYJFBOIT+N0mqca37S8hA9hCJyD3p0AM40dD5M5ARAxpAT7+oqOXkPzf
zLtCTaHYJK3+WAce121Br4NuQJPqYPVxniUPohT4YxFTqB7vwX2C4/gZ2ldpHtlg
JVAHT96nOsnlz+EPa5GtwxtALD43CwOlWQIDAQAB
-----END RSA PUBLIC KEY-----"""

_EXP_1 = """
-----BEGIN RSA PUBLIC KEY-----
MIIBCAKCAQEA2CzMh5UOtdozYHY5rIe0NKE0dDxuEAyuZBsB6kwoMZd0x9gnbN18
K0eepXnFF05VxNNXRBt90Giy6E0iE/x9FOTNB6a71leCBgVCseAVgyEGbuXotSwg
zZkV1jpL81v4bkqLycu9cqaThJUBwxWelSW63eK3izrLrV0tfbjdDO64HZcGQ/VL
jmCgavVFrs3XiiAZAfOb2uLC4NYfZvej/Se0fC/kWlitCvXi/S73LkXfWD4HukfP
RZ61hWAEfQOhflqhGm1/ty5tNK4cXCvH0cXUz6L8YTUgxxlgW1LO508SjzCQLkgB
XSUqHimDSVLugBG2B96P9dmzM4SKk1qWGQIBAQ==
-----END RSA PUBLIC KEY-----"""

_EXP_3 = """-----BEGIN RSA PUBLIC KEY-----
MIIBCAKCAQEAyfPe/hnGvfpGZKScWzwJHn7E8sqzc7Ou5bf+DLLKmHF3TD5w4rHc
8IYS/eH+2pNzyot8cxQzp3iVXKMc8vPWpNYI30ZvEN4+5zOzXR+k3DErL0AIVHT5
KEIwhuIW9oEtq7mQIeaevZeYc7iu1gNAPelzWKE7DYsjAif+92qyQqB+SuYxOPqg
vrqB+T6sWBo6difvlJTq1ai/1UTAFVlldBErDObcZBslfUZuCEEv7ZKH3AOT++vB
+8ID7U8j6L3/Agc4hg2waauUl9gsuG8qTKZnYYJU09KkqXLbrM3NnyvRQQUwRbCc
gwiC17UdQU0eEfEt4BV0E03i57PtHTj8jwIBAw==
-----END RSA PUBLIC KEY-----"""

_FERMAT = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAkGbTtoSrOJmrwu9FV3A3xDfxNn3EnSO94M9+QIL3qJjjIMh30xrA
dra5ZsXjhJrRApI0X+qArvTQVv6/n9YqEoAPmF7n46yJ1TtYETFzGCjqk1sDZ8rV
Enq4bxPHk0EQcFiQIn6iwTPOjeidD2WKUNIVeJWI/2X8Ms3ITdt+P4jV0DVeA6rd
R31ClG+HGos1OdTA+8nMwDId0jA/Kv8MOPFBLf24p9OB8fzXP2Uno0CSSrZLktJC
ouOcPzGgBB5sZZFHxpsrf76uJNULBrjC9Pbxx3ogpGVy1L5CC9v8qk3L44qQpi4g
/PC9wWNsK+NPr/tiq4+S3uB369Ye1n+0ywIDAQAB
-----END RSA PUBLIC KEY-----"""

_MANY_ZEROS = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHMgAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAATjsQIDAQAB
-----END RSA PUBLIC KEY-----"""

_PRIME_N = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAqQSg27883tGr5jtyOaZkEn597cuw1Wz4wWuFp1quvHOyiMId7L7m
KHh2G+WQaEEBKl2A/M/tXgdfbrY0NnW3SMIZ9PMTWJNjtAqjBKVBDXDJbJhOpvya
gL4HBKR6cnB0TE+3m0co6o98xRT7eFBP4V9WyZYIG15XDruFvGkgeqmXefqf5BB5
Erquu6RePYNt25I3SFM12kZTW+HcrDyj34CO4Jxkw5JI5bUtP9wV5ocr/Z5FmvmI
Di3eNbHBVteLN3BIuFax8JQvpcdwEjy7Qdro5Ad3a3Ld4//2Vn/mAkGPop/HmJme
wI1poiKh+VgF87bloijO+izBYk/eo9ZWWQIDAQAB
-----END RSA PUBLIC KEY-----"""

_RFC = """-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAGb9ECWmEzf6FQbrBZ9w7lshQhqowtrbLDFw4rXAxZuE=
-----END PUBLIC KEY-----"""

_ROCA = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAkTKtIR/MDftNrkgyashkwifks5Swm9HEkw4ZcCijyQdpTStInk9p
dUrq4zjG6tk5xX9AaYXLu47fmiBVzClGvAXTZbpn6JbG1IERUs+i0pBRT5CzUu7v
J/63L72NzVvJFaT0SUE5zByhCjJE+pflMnX1e1UptOdnN5AHeY4RKkugVse3XO2x
Ms3yH3vTyZdtnaOIFRU0d6E7PrsgRtEAqFHcAGmPUw0ZOW8A++8sS/FlnrxMf9lV
a1/8k/A8otPfrNIipfAoq0MKJ+oxE2wML1DDxIGTGmNaN3gPANJyeuca7ptA+NGq
5oU1x3pWMXgSvrVSXUooNk8xIkrKxSz3LQIDAQAB
-----END RSA PUBLIC KEY-----"""

_SMALL_FACTORS = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAp8qz/SX4rPy4d48/J9ejq7KBHokrV73jHpgkh5vGHUx2TPDOF056
praiZ+lG2MXikOr5jfzoqyphzIj///8GVZs1h9mdp2AQplXUg+Pb39pZ/TZ1EryA
kqvNb8V71RrPtclZRkKJHm1ob2P/A/Bf0pSxkh6z0W6zm+iDfvqOrpvbsP8hxq02
jeGrqPTEtzMX4sm4yMlf3xGEBF9HOaYsOE3TNlhll1qhMH+RFdXUTxnHtEHQ/iiy
oWmZjGVK2Zp7Q8+XpwxhW+F19dR29n/4yYtFu9WNA2OhoXxA5y+FYxoJg0Jl8Kql
/RD9026hAlXbbr4mImImsUDiIo5TGVxv3QIDAQAB
-----END RSA PUBLIC KEY-----"""

_SQUARE_MODULUS = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAxcHDv7trhGAHcVv/k/ORtkIbMVdeotjv1RdcQWwIv4cp1lXGG7IT
GJ43DJGFw3rdb+SNi0etQ3ipjLLvoQ2lsj4u3zqbuuRu6usGoCcOod44DGOfCIGq
K2Oxu6jewuyNgMPyN87bJhJwi/8wV0JpQbLM2BBl5hraUsvrwNqyvI0EAzXLA6ff
rmZ+RQPpL1uQ4fztkrKqrfFkKCMrKmKcJQnC4RpfdE/aQ+OKXFtfSEhllASVFBMI
OLfKZwV4GCJCaUcishZDSntPx3lNjozKeIn0kFDwlNtz7JiQ06UzhbV0Owk7RSnH
SIKunkudJuUU6RIcKp6bPPgT/oXDICl5GQIDAQAB
-----END RSA PUBLIC KEY-----"""

_TOO_SMALL = """-----BEGIN RSA PUBLIC KEY-----
MEgCQQDf3ZUn4aBDoJdJ6dJM1X0pZlz8LWf9QD0wYsB9rAahvoSNN3JVi+xRBiI/
7UDBtWAqeun5h44V43Rx9QJVlPYdAgMBAAE=
-----END RSA PUBLIC KEY-----"""

_UNUSUAL_SIZE = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEBWTyUOuiyrAnulzRBN8x3FlzdzaRGaa1DbNUpCaFNUlZBzvJUomP3
wfSK44CoC84nTM/fK0Q5nKEwls0nycRciAnNlawuBkEt6o3Tmw0aWcGxbQoJ9lVK
oXrG1yUm4nvypt67APitktGqh4ew3vsa94PtZOpW3X4QYFcysPeQTyTwZRunTIcx
DZCuUYi3z7tMdUlLPw5iS3sLxinJ6IK+KV1f+5nPxueA4u3Li/xbc4zOimjcfamP
exIOpnGpbcrigmhTzVNQRZKy43WmKdCNHNkVorzJTn34jQxZ20ImgkpH8oWBCc8f
SNGBR2tvSyYvV76BopMcj0t3+VpME5cUlwIDAQAB
-----END RSA PUBLIC KEY-----"""


_BAD_KEYS = (
    _DEBIAN_SSL,
    _EXP_1,
    # _EXP_3,
    _FERMAT,
    _MANY_ZEROS,
    _PRIME_N,
    _RFC,
    _ROCA,
    _SMALL_FACTORS,
    _SQUARE_MODULUS,
    # _TOO_SMALL,
    # _UNUSUAL_SIZE,
)


@util.test_log
def main():
    test_pubkeys()
    test_badkeys()


@util.test_log
def test_pubkeys():
    k_sig, k_enc = rsa_w.construct(2048)

    key_info = badkeys.detectandcheck(k_sig.public_key().export_key("PEM").decode())
    assert not key_info.get("results"), f"{key_info.get('results')}"

    key_info = badkeys.detectandcheck(k_enc.public_key().export_key("PEM").decode())
    assert not key_info.get("results"), f"{key_info.get('results')}"


@util.test_log
def test_badkeys():
    for bad_key in _BAD_KEYS:
        key_info = badkeys.detectandcheck(bad_key)
        assert key_info.get("results")


if __name__ == "__main__":
    main()
